[package]
name = "disboard"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
num-traits = "0.2.19"
qhull = { git = "https://github.com/eniraa/qhull-rs.git" }
rand = "0.8.5"

[dev-dependencies]
approx = "0.5.1"
